.\" Manpage for ayacc
.\" Send an email to www.fe32gr23@gmail.com to correct errors or typos.
.TH AYACC 1 "September 4, 2022" "Ancient Yacc 1.0" "User Commands"
.SH NAME
ayacc \- the original version of Yacc, developed at Bell Labs
.SH SYNOPSIS
ayacc [OPTIONS]

ayacc [-d]

ayacc [-v]

ayacc [-y PATH]
.SH DESCRIPTION
ayacc (Ancient Yacc) is the orignal version of Yacc (Yet Another Compiler Compiler), developed at Bell Labs
for UNIX V3 in the 1970s. ayacc is based on the UNIX/32V version of Yacc. The only difference between
the two, other than the name,is that ayacc has been updated for use with modern systems, since it was
written in K&R C.
.SH COPYRIGHT
Copyright (c) 2022 calmsacibis995. Ancient Yacc is licensed under the BSD License.
This is free software; there is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH SEE ALSO
bison(1), yacc(1), byacc(1)
.SH AUTHOR
Written by calmsacibis995 (www.fe32gr23@gmail.com)
